### ISSUE TITLE
Sign Up for Ethical Hacking Course

### ISSUE THREAD

**Issue by newworldhost** [newworldhost/newworldhost#1]
_**User Story 1: Sign Up for Ethical Hacking Course**_

- [ ] As a user, I want to sign up for an ethical hacking course so that I can learn how to protect systems and networks.

**Acceptance Criteria:**

- [ ] User should be able to create an account.

- [ ] User should be able to select and enroll in a course.

- [ ] User should receive a confirmation email upon successful enrollment.

**Task List:**

- [ ] Design and implement a sign-up page.

- [ ] Create a course selection and enrollment process.

- [ ] Implement email confirmation functionality.
